Move all methods into the Miner class

diff --git a/miner b/miner
--- a/miner
+++ b/miner
@@ -3,112 +3,80 @@
 
 namespace Arionum\Miner;
 
-echo "######################\n";
-echo "# Arionum Miner v0.2 #\n";
-echo "# www.arionum.com    #\n";
-echo "######################\n\n";
-
 error_reporting(0);
-
-if (!extension_loaded("gmp")) {
-    die("gmp php extension missing");
-}
-
-if (!extension_loaded("openssl")) {
-    die("openssl php extension missing");
-}
-
-if (floatval(phpversion()) < 7.2) {
-    die("The minimum php version required is 7.2");
-}
-
-if (!defined("PASSWORD_ARGON2I")) {
-    die("The php version is not compiled with argon2i support");
-}
-
 ini_set("memory_limit", "5G");
 
 $type = trim($argv[1]);
-
 $node = trim($argv[2]);
 $public_key = trim($argv[3]);
 $private_key = trim($argv[4]);
 
-
-if (empty($type) || empty($public_key) || empty($node) || ($type == "solo" && empty($private_key))) {
-    echo "Usage:
-
-For Solo mining: ./miner solo <node> <public_key> <private_key>
-
-For Pool mining: ./miner pool <pool-address> <your-address>\n\n";
-    exit;
-}
-if ($type == "pool") {
-    $private_key = $public_key;
-}
-
-//all credits for this base58 functions should go to tuupola / https://github.com/tuupola/base58/
-function baseConvert(array $source, $source_base, $target_base)
-{
-    $result = [];
-    while ($count = count($source)) {
-        $quotient = [];
-        $remainder = 0;
-        for ($i = 0; $i !== $count; $i++) {
-            $accumulator = $source[$i] + $remainder * $source_base;
-            $digit = (integer)($accumulator / $target_base);
-            $remainder = $accumulator % $target_base;
-            if (count($quotient) || $digit) {
-                array_push($quotient, $digit);
-            };
-        }
-        array_unshift($result, $remainder);
-        $source = $quotient;
-    }
-    return $result;
-}
-
-function base58_decode($data, $integer = false)
-{
-    $data = str_split($data);
-    $data = array_map(function ($character) {
-        $chars = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
-        return strpos($chars, $character);
-    }, $data);
-    /* Return as integer when requested. */
-    if ($integer) {
-        $converted = baseConvert($data, 58, 10);
-        return (integer)implode("", $converted);
-    }
-    $converted = baseConvert($data, 58, 256);
-    return implode("", array_map(function ($ascii) {
-        return chr($ascii);
-    }, $converted));
-}
+new Miner($type, $node, $public_key, $private_key);
 
 class Miner
 {
-    private $public_key;
-    private $private_key;
+    public const VERSION = 'v0.2';
+
+    private $publicKey;
+    private $privateKey;
     private $speed;
-    private $avg_speed;
+    private $avgSpeed;
     private $node;
     private $block;
     private $difficulty;
     private $counter;
-    private $alltime;
+    private $allTime;
+    private $beginTime;
     private $type;
     private $limit;
     private $worker;
-    private $last_update;
+    private $lastUpdate;
     private $submit;
     private $confirm;
     private $found;
 
+    public function __construct($type, $node, $public_key, $private_key)
+    {
+        $this->outputHeader();
+
+        $this->checkDependencies();
+
+        if (empty($type) || empty($public_key) || empty($node) || ($type == "solo" && empty($private_key))) {
+            echo "Usage:
+
+For Solo mining: ./miner solo <node> <public_key> <private_key>
+
+For Pool mining: ./miner pool <pool-address> <your-address>\n\n";
+            exit;
+        }
+
+        if ($type == "pool") {
+            $private_key = $public_key;
+        }
+
+        //checking if the address is valid
+        if ($type == "pool") {
+            $dst_b = $this->base58_decode($public_key);
+            if (strlen($dst_b) != 64) {
+                die("ERROR: Invalid Arionum address!");
+            }
+        }
+
+        $worker = uniqid();
+
+        $this->prepare($public_key, $private_key, $node, $type, $worker);
+        $res = $this->update();
+        if (!$res) {
+            die("ERROR: Could not get mining info from the node");
+        }
+
+        $this->run();
+    }
+
     public function prepare($pub, $priv, $node, $type, $worker)
     {
-        $this->public_key = $pub;
-        $this->private_key = $priv;
+        $this->publicKey = $pub;
+        $this->privateKey = $priv;
         $this->node = $node;
         $this->type = $type;
         $this->worker = $worker;
@@ -120,11 +88,13 @@ class Miner
 
     public function update()
     {
-        $this->last_update = time();
+        $this->lastUpdate = time();
+
         echo "--> Updating mining info\n";
+
         $extra = "";
         if ($this->type == "pool") {
-            $extra = "&worker=".$this->worker."&address=".$this->private_key."&hashrate=".$this->speed;
+            $extra = "&worker=".$this->worker."&address=".$this->privateKey."&hashrate=".$this->speed;
         }
         $res = file_get_contents($this->node."/mine.php?q=info".$extra);
 
@@ -137,11 +107,13 @@ class Miner
         $this->difficulty = $data['difficulty'];
         if ($this->type == "pool") {
             $this->limit = $data['limit'];
-            $this->public_key = $data['public_key'];
+            $this->publicKey = $data['public_key'];
         } else {
             $this->limit = 240;
         }
+
         echo "Min DL: ".$this->limit."\n";
+
         return true;
     }
 
@@ -151,14 +123,13 @@ class Miner
         $argon = substr($argon, 30);
         echo "--> Submitting nonce $nonce / $argon\n";
 
-
         $postdata = http_build_query(
             [
                 'argon'       => $argon,
                 'nonce'       => $nonce,
-                'private_key' => $this->private_key,
-                'public_key'  => $this->public_key,
-                'address'     => $this->private_key,
+                'private_key' => $this->privateKey,
+                'public_key'  => $this->publicKey,
+                'address'     => $this->privateKey,
             ]
         );
 
@@ -187,25 +158,27 @@ class Miner
 
     public function run()
     {
-        $this->alltime = microtime(true);
-        $this->begintime = time();
+        $this->allTime = microtime(true);
+        $this->beginTime = time();
         $it = 0;
         $this->counter = 0;
         $start = microtime(true);
         while (1) {
             $this->counter++;
-            if (time() - $this->last_update > 2) {
+
+            if (time() - $this->lastUpdate > 2) {
                 echo "--> Last hash rate: ".$this->speed." H/s   ".
-                    "Average: ".$this->avg_speed." H/s  ".
+                    "Average: ".$this->avgSpeed." H/s  ".
                     "Total hashes: ".$this->counter."  ".
                     "Mining Time: ".(time() - $this->begintime)."  ".
                     "Shares: ".$this->confirm." ".
                     "Finds: ".$this->found."\n";
                 $this->update();
             }
+
             $nonce = base64_encode(openssl_random_pseudo_bytes(32));
             $nonce = preg_replace("/[^a-zA-Z0-9]/", "", $nonce);
-            $base = $this->public_key."-".$nonce."-".$this->block."-".$this->difficulty;
+            $base = $this->publicKey."-".$nonce."-".$this->block."-".$this->difficulty;
             $argon = password_hash(
                 $base,
                 PASSWORD_ARGON2I,
@@ -240,27 +213,91 @@ class Miner
                 $end = microtime(true);
 
                 $this->speed = 10 / ($end - $start);
-                $this->avg_speed = $this->counter / ($end - $this->alltime);
+                $this->avgSpeed = $this->counter / ($end - $this->allTime);
                 $start = $end;
             }
         }
     }
-}
 
-//checking if the address is valid
-if ($type == "pool") {
-    $dst_b = base58_decode($public_key);
-    if (strlen($dst_b) != 64) {
-        die("ERROR: Invalid Arionum address!");
+    /**
+     * @param array $source
+     * @param mixed $source_base
+     * @param mixed $target_base
+     * @return array
+     *
+     * @author Mika Tuupola
+     * @link   https://github.com/tuupola/base58
+     */
+    public function baseConvert(array $source, $source_base, $target_base)
+    {
+        $result = [];
+        while ($count = count($source)) {
+            $quotient = [];
+            $remainder = 0;
+            for ($i = 0; $i !== $count; $i++) {
+                $accumulator = $source[$i] + $remainder * $source_base;
+                $digit = (integer)($accumulator / $target_base);
+                $remainder = $accumulator % $target_base;
+                if (count($quotient) || $digit) {
+                    array_push($quotient, $digit);
+                };
+            }
+            array_unshift($result, $remainder);
+            $source = $quotient;
+        }
+        return $result;
+    }
+
+    /**
+     * @param mixed $data
+     * @param bool  $integer
+     * @return int|string
+     *
+     * @author Mika Tuupola
+     * @link   https://github.com/tuupola/base58
+     */
+    public function base58Decode($data, $integer = false)
+    {
+        $data = str_split($data);
+        $data = array_map(function ($character) {
+            $chars = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
+            return strpos($chars, $character);
+        }, $data);
+        /* Return as integer when requested. */
+        if ($integer) {
+            $converted = $this->baseConvert($data, 58, 10);
+            return (integer)implode("", $converted);
+        }
+        $converted = $this->baseConvert($data, 58, 256);
+        return implode("", array_map(function ($ascii) {
+            return chr($ascii);
+        }, $converted));
+    }
+
+    public function checkDependencies()
+    {
+        if (!extension_loaded("gmp")) {
+            die("The GMP PHP extension is missing.");
+        }
+
+        if (!extension_loaded("openssl")) {
+            die("The OpenSSL PHP extension is missing.");
+        }
+
+        if (floatval(phpversion()) < 7.2) {
+            die("The minimum PHP version required is 7.2.");
+        }
+
+        if (!defined("PASSWORD_ARGON2I")) {
+            die("The PHP version is not compiled with argon2i support.");
+        }
+    }
+
+    public function outputHeader()
+    {
+        echo "######################\n";
+        echo "# Arionum Miner ".self::VERSION." #\n";
+        echo "# www.arionum.com    #\n";
+        echo "######################\n\n";
     }
 }
-
-$worker = uniqid();
-
-$miner = new Miner;
-$miner->prepare($public_key, $private_key, $node, $type, $worker);
-$res = $miner->update();
-if (!$res) {
-    die("ERROR: Could not get mining info from the node");
-}
-$miner->run();
