updated miner

diff --git a/miner b/miner
--- a/miner
+++ b/miner
@@ -6,14 +6,27 @@ echo "# www.arionum.com    #\n";
 echo "######################\n\n";
 error_reporting(0);
 if (!extension_loaded("gmp")) die("gmp php extension missing");
-if(floatval(phpversion())<7.2) api_err("The minimum php version required is 7.2");
+if(floatval(phpversion())<7.2) die("The minimum php version required is 7.2");
+if (!defined("PASSWORD_ARGON2I")) die("The php version is not compiled with argon2i support");
 
 ini_set("memory_limit","5G");
 
-$node=trim($argv[1]);
-$public_key=trim($argv[2]);
-$private_key=trim($argv[3]);
-if(empty($node)||empty($public_key)||empty($private_key)) die("Usage: ./miner <node> <public_key> <private_key>\n");
+$type=trim($argv[1]);
+
+$node=trim($argv[2]);
+$public_key=trim($argv[3]);
+$private_key=trim($argv[4]);
+
+
+if(empty($type)||empty($public_key)||empty($node)||($type=="solo"&&empty($private_key))){
+echo "Usage:
+
+For Solo mining: ./miner solo <node> <public_key> <private_key>
+
+For Pool mining: ./miner pool <pool-address> <your-address>\n\n";
+exit;
+}
+if($type=="pool") $private_key=$public_key;
 
 
 class Miner {
@@ -24,21 +37,37 @@ class Miner {
 	private $block;
 	private $difficulty;
 	private $counter;
-	public function prepare($pub, $priv, $node){
+	private $type;
+	private $limit;
+	private $worker;
+	private $last_update;
+	public function prepare($pub, $priv, $node, $type,$worker){
 				$this->public_key=$pub;
 		                $this->private_key=$priv;
 				$this->node=$node;
-				
+				$this->type=$type;
+				$this->worker=$worker;				
 	}
 
 	public function update(){
+		$this->last_update=time();
 		echo "--> Updating mining info\n";
-		 $res=file_get_contents($this->node."/mine.php?q=info");
+		$extra="";
+		if($this->type=="pool") $extra="&worker=".$this->worker."&address=".$this->private_key."&hashrate=".$this->speed;
+		 $res=file_get_contents($this->node."/mine.php?q=info".$extra);
+
         	 $info=json_decode($res,true);
        		 if($info['status']!="ok") return false;
 		$data=$info['data'];
 		$this->block=$data['block'];
 		$this->difficulty=$data['difficulty'];
+		if($this->type=="pool"){
+			$this->limit=$data['limit'];
+			$this->public_key=$data['public_key'];
+		} else {
+			$this->limit=240;
+		}
+		echo "Min DL: ".$this->limit."\n";
 		return true;
 	}
 	private function submit($nonce,$argon){
@@ -54,7 +83,8 @@ class Miner {
 				'argon' => $argon,
 				'nonce' => $nonce,
 				'private_key' => $this->private_key,
-				'public_key' => $this->public_key
+				'public_key' => $this->public_key,
+				'address'=> $this->private_key,
 			)
 		);
 		
@@ -69,10 +99,9 @@ class Miner {
 		$context  = stream_context_create($opts);
 		
 		$res = file_get_contents($this->node."/mine.php?q=submitNonce", false, $context);
-
 		$data=json_decode($res,true);
-		
-		if($data['status']=="ok") echo "\n--> Nonce confirmed. Block mined.\n";
+
+		if($data['status']=="ok") echo "\n--> Nonce confirmed.\n";
 		else echo "--> The nonce did not confirm.\n\n";
 		
 	}
@@ -81,7 +110,7 @@ class Miner {
 		$start=microtime(true);
 		while(1){
 		$this->counter++;
-		if($this->counter==1000) {
+		if(time()-$this->last_update>2) {
 			echo "--> Hash rate: ".$this->speed." H/s\n";
 			$this->update();
 			$this->counter=0;
@@ -90,6 +119,7 @@ class Miner {
         	$nonce = preg_replace("/[^a-zA-Z0-9]/", "", $nonce);
 			$base=$this->public_key."-".$nonce."-".$this->block."-".$this->difficulty;
 			$argon=password_hash($base, PASSWORD_ARGON2I, array('memory_cost' => 16384, "time_cost"=>4, "threads"=>4));
+
 			$hash=$base.$argon;
 			for($i=0;$i<5;$i++){
 				$hash=hash("sha512",$hash,true);
@@ -103,9 +133,7 @@ class Miner {
 			$duration=ltrim($duration, '0');
 						
 			$result=gmp_div($duration,$this->difficulty);
-	
-			if($result>0&&$result<=240){ 
-				
+			if($result>0&&$result<=$this->limit){
 				$this->submit($nonce,$argon);		
 				
 			}
@@ -126,10 +154,10 @@ class Miner {
 
 
 
-
+$worker=uniqid();
 
 $miner= new Miner;
-$miner->prepare($public_key,$private_key, $node);
+$miner->prepare($public_key,$private_key, $node,$type,$worker);
 $res=$miner->update();
 if(!$res) die("ERROR: Could not get mining info frm the node");
 
